apiVersion: v1
kind: Pod
metadata:
  name: virgin-pod
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image:  ghcr.io/0252859/cis-92-cloud-dev-ops-spring-23:milestone-4.11
    key: SECRET_KEY
    value: superspecialkey
  
  ports:
    - containerPort: 80