apiVersion: v1
kind: Pod
metadata:
  name: lizzyspod
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image:  ghcr.io/0252859/cis-92-cloud-dev-ops-spring-23:milestone-5.1
    env:
    - name: SECRET_KEY
      value: blahblahblah
    - name: PORT
      value: '80'
    - name: DB_NAME
      value: 'mysite'
    - name: DB_USER
      value: 'postgres'
    - name: DB_PASSWORD
      value: 'django'
    - name: DB_HOST
      value: 'postgres'


    resources: 
      limits: 
        cpu: 250m
        memory: 512Mi
        ephemeral-storage: 10Mi
    
    livenessProbe: 
      httpGet: 
        path: /polls/
        port: 80